I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenario/game_battle.rpy", line 146, in script call
    "Наёмник нанес вам [random] единиц урона."
  File "game/images/resources/inventory.rpy", line 115, in script
    label update_sprite_clothes(var_name):
TypeError: Missing required positional arguments: 'var_name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenario/game_battle.rpy", line 146, in script call
    "Наёмник нанес вам [random] единиц урона."
  File "game/images/resources/inventory.rpy", line 115, in script
    label update_sprite_clothes(var_name):
  File "D:\RenPy\renpy\ast.py", line 1081, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "D:\RenPy\renpy\ast.py", line 296, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "D:\RenPy\renpy\ast.py", line 232, in apply
    raise TypeError(
TypeError: Missing required positional arguments: 'var_name'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Durka Simulator 0.4.2
Fri Jan 12 13:20:59 2024
